### ISSUE TITLE
FFGL plugin cannot be recognized in Resolume

### ISSUE THREAD

**Issue by UFeatherSerpent** [Syphon/FreeFrameGL#1]
Hello, Guy!
I want to do some test on the FFGL plugin in Resolume Arena. 
I follow the instruction and name the whole folder of "syphon client" into syphon client.bundle,
but still the Resolume FFGL plugin still cannot recognized the plugin. 
Like in this video 00:37, https://vimeo.com/14531751, I cannot find the bundle under FFGL sources.
(I am sure the bundle is sure on the right position of the host application). 

Mine is a mac with OSX 10.9.3. 
I download the FFGL zip from "https://github.com/Syphon/FreeFrameGL" here. 

Please advice me solution to that, thanks for your guidance. 
Your repository is really helpful for visual creative project. 

Casberu

**Comment by bangnoise** [comment]
Hi - it sounds like you might be trying to install the source from this repository. The distribution is hosted on the old google code site, but I've just added a [release](https://github.com/Syphon/FreeFrameGL/releases/latest)  here.

That said, Resolume supports Syphon natively, and there is no need to install these plugins.
